"""add incident groups

Revision ID: 956495874477
Revises: 3f799cbb6bb0
Create Date: 2026-06-30 18:49:06.462099

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956495874477'
down_revision: str | None = '3f799cbb6bb0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_groups',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='group_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='group_status'), nullable=False),
    sa.Column('leader_alert_id', sa.Uuid(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_groups_leader_alert_id'), 'incident_groups', ['leader_alert_id'], unique=False)
    op.create_index(op.f('ix_incident_groups_service_id'), 'incident_groups', ['service_id'], unique=False)
    op.add_column('alerts', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_alerts_group_id'), 'alerts', ['group_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'incident_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_group_id'), table_name='alerts')
    op.drop_column('alerts', 'group_id')
    op.drop_index(op.f('ix_incident_groups_service_id'), table_name='incident_groups')
    op.drop_index(op.f('ix_incident_groups_leader_alert_id'), table_name='incident_groups')
    op.drop_table('incident_groups')
    # ### end Alembic commands ###
