"""add investigation cost fields

Revision ID: e803ef1617c7
Revises: a1c4e7b90d2f
Create Date: 2026-07-05 11:43:18.230071

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e803ef1617c7'
down_revision: str | None = 'a1c4e7b90d2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.add_column('investigations', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('investigations', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'output_tokens')
    op.drop_column('investigations', 'input_tokens')
    op.drop_column('investigations', 'cost_usd')
    # ### end Alembic commands ###
